booking/urls.py
from django.conf.urls import url
from . import views



app_name = 'booking'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hotels$', views.hotels, name='hotels'),
    url(r'^(?P<hotel_id>[0-9]+)/$', views.hotel_detail, name='hotel_detail'),
    url(r'^(?P<hotel_id>[0-9]+)/delete$', views.hotel_delete, name='hotel_delete'),
    url(r'^rooms/(?P<room_id>[0-9]+)/$', views.room_detail, name='room_detail'),
    url(r'^rooms/(?P<room_id>[0-9]+)/delete$', views.room_delete, name='room_delete'),
    url(r'^rooms/(?P<room_id>[0-9]+)/bookit$', views.room_bookit, name='room_bookit'),
    url(r'^bookings/(?P<booking_id>[0-9]+)/confirm/$', views.booking_confirm, name='booking_confirm'),
    url(r'^bookings/(?P<booking_id>[0-9]+)/cancel/$', views.booking_cancel, name='booking_cancel'),
    #url(r'^register$', views.register, name='register'),
    url(r'^hotels/add$', views.hotel_add, name='hotel_add'),
    url(r'^rooms/add$', views.room_add, name='room_add'),
    url(r'^room_types/add$', views.room_type_add, name='room_type_add'),
    url(r'^users/(?P<username>\w+)/$', views.user_profile, name='user_profile'),
    url(r'^users/(?P<username>\w+)/bookings$', views.user_bookings, name='user_bookings'),
    url(r'^users/(?P<username>\w+)/payments', views.user_payments, name='user_payments'),
    url(r'^payments/(?P<payment_id>[0-9]+)/$', views.pay_bill, name='pay_bill'),
    url(r'^hotel_chains/add$', views.hotel_chain_add, name='hotel_chain_add'),
]

hotels_booking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from booking import urls
admin.autodiscover()
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^booking/', include('booking.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#register

booking/forms.py
from django import forms
from .models import *
#from booking.models import *

#class UserForm(forms.ModelForms):
  #  class Meta:
   #     model = User
  #      fields = ('name', 'surname', 'address', 'email', 'phone_number')

class HotelForm(forms.ModelForm):
    class Meta:
        model = Hotel
        fields = ('hotel_chain', 'country_code', 'name', 'email', 'address', 'city', 'email', 'phone_number', 'star_rating', 'url')


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = Image
        fields = ('image', )


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ('hotel', 'room_type', 'description', 'price')


class RoomTypeForm(forms.ModelForm):
    class Meta:
        model = Room_Type
        fields = ('room_type', 'room_standard', 'smoking_in')


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('start_date', 'end_date', 'description')


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('guest', 'booking',)


class HotelChainForm(forms.ModelForm):
    class Meta:
        model = Hotel_Chain
        fields = ('chain_name',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('context', 'rating',)


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('hotel',)

booking/views.py
from django.forms import modelformset_factory
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Avg
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from booking.forms import *
from booking.models import *
from django.core.mail import EmailMessage

def hotels(request):
    hotels_list = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query = request.GET['q']
        hotels_list = Hotel.objects.filter(Q(name__icontains=query) |
                                      Q(city__icontains=query) |
                                      Q(country_code__icontains=query)
                                      )
    else:
        hotels_list = Hotel.objects.all()

    paginator = Paginator(hotels_list, 5)
    page_var = 'page'
    page = request.GET.get(page_var)
    try:
        hotels = paginator.page('page')
    except PageNotAnInteger:
        hotels = paginator.page(1)
    except EmptyPage:
        hotels = paginator.page(paginator.num_pages)

    context = {'hotels': hotels}
    return render(request, 'booking/hotels.html', context)


def index(request):
    return render(request, 'booking/index.html', {})

email = EmailMessage('title', 'body', to=[email])
email.send()



def hotel_detail(request, hotel_id):
    hotel = get_object_or_404(Hotel, id=hotel_id)
    rooms_list = Room.objects.filter(hotel=hotel_id)
    paginator = Paginator(rooms_list, 5)
    page_var = 'page'
    page = request.GET.get(page_var)
    try:
        rooms = paginator.page(page)
    except PageNotAnInteger:
        rooms = paginator.page(1)
    except EmptyPage:
        rooms = paginator.page(paginator.num_pages)

    context = {
        'hotel' : hotel,
        'rooms' : rooms,
    }
    return render(request, 'booking/hotel_detail.html', context)



def room_detail(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    images = Image.objects.filter(room=room_id)
    image = images[0]
    comments_list = Comment.objects.filter(room=room_id).order_by('-date')
    paginator = Paginator(comments_list, 5)
    page_var = 'page'
    page = request.GET.get(page_var)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    context = {
        'room': room,
        'image': image,
        'comments': comments,
        'page_var': page_var,
    }
    if request.method == 'POST':
        return comment_add(request, room_id)

    return render(request, 'booking/room_detail.html', context)


def comment_add(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    hotel = get_object_or_404(Hotel, id=room.hotel.id)
    if request.method == 'POST':
        commentForm = CommentForm()
        comment_form = commentForm.save(commit=False)
        comment_form.user = request.user
        comment_form.room = room
        comment_form.context = request.POST.get('content')

        ratingForm = RatingForm()
        rating_form = ratingForm.save(commit=False)
        rating_form.rate = request.POST.get('rating')
        rating_form.hotel = hotel
        rating_form.save()
        rate_avg = Rating.objects.filter(hotel_id=rating_form.hotel.id).aggregate(Avg('rate'))
        hotel.star_rating = rate_avg.get('rate__avg')
        hotel.save()
        comment_form.rating = rating_form
        comment_form.save()


    return redirect('booking:room_detail', room.id)



def room_type_add(request):
    if request.method == 'POST':
        room_type_form = RoomTypeForm(request.POST)
        if room_type_form.is_valid():
            room_type_form.save(commit=False)
            room_type_form.save()

            return render(request, 'booking/index.html', {})

    else:
        room_type_form = RoomTypeForm()
        return render(request, 'booking/room_type_add.html', {'roomTypeForm' : room_type_form})


def hotel_add(request):
    ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=3)

    if request.method == 'POST':
        hotelForm = HotelForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES, queryset=Image.objects.none())

        if hotelForm.is_valid() and formset.is_valid():
            hotel_form = hotelForm.save(commit=False)
            hotel_form.owner = request.user
            hotel_form.save()

            for form in formset.cleaned_data:
                try:
                    image = form['image']
                    photo = Image(hotel=hotel_form, image=image)
                    photo.save()
                except KeyError:
                    pass

            try:
                image = formset.cleaned_data[0]['image']
                hotel_form.avatar = image
                hotel_form.save()
            except KeyError:
                hotel_form.delete()
                return clear_hotel_add_form(request, ImageFormSet, 'Select at least 1 Image!')

            hotels = Hotel.objects.all()
            return render(request, 'booking/hotels.html', {'hotels' : hotels})

        else:
            return clear_hotel_add_form(request, ImageFormSet, 'Invalid Form!')

    else:
        return clear_hotel_add_form(request, ImageFormSet, '')


def clear_hotel_add_form(request, formSet, title):
    title = title
    ImageFormSet = formSet
    hotelForm = HotelForm()
    formset = ImageFormSet(queryset=Image.objects.none())
    context = {'hotelForm': hotelForm, 'formset': formset, 'title': title}
    return render(request, 'booking/hotel_add.html', context)


def hotel_delete(request, hotel_id):
    hotel = get_object_or_404(Hotel, id=hotel_id)
    hotel.delete()
    return redirect('booking:hotels')


def room_delete(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    room.delete()
    return redirect('booking:index')


def room_add(request):
    ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=3)

    if request.method == 'POST':
        roomForm = RoomForm(request.POST)
        formset = ImageFormSet(request.POST, request.FILES, queryset=Image.objects.none())

        if roomForm.is_valid() and formset.is_valid():
            room_form = roomForm.save(commit=False)
            room_form.save()

            for form in formset.cleaned_data:
                try:
                    image = form['image']
                    photo = Image(room=room_form, image=image)
                    photo.save()
                except KeyError:
                    pass

            try:
                image = formset.cleaned_data[0]['image']
                room_form.avatar = image
                room_form.save()
            except KeyError:
                room_form.delete()
                return clear_room_add_form(request, ImageFormSet, 'Select at least 1 Image!')

            return redirect('booking:index')

        else:
            return clear_room_add_form(request, ImageFormSet, 'Invalid form!')

    else:
        return clear_room_add_form(request, ImageFormSet, '')


def clear_room_add_form(request, formSet, title):
    title = title
    ImageFormSet = formSet
    roomForm = RoomForm()
    formset = ImageFormSet(queryset=Image.objects.none())
    context = {'roomForm': roomForm, 'formset': formset, 'title': title}
    return render(request, 'booking/room_add.html', context)

def user_profile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'booking/user_profile.html', {'user' : user})


def room_bookit(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    hotel = get_object_or_404(Hotel, id=room.hotel.id)

    if request.user.is_authenticated():
        if request.method == 'POST':
            bookingForm = BookingForm(request.POST)
            if bookingForm.is_valid():
                booking_form = bookingForm.save(commit=False)
                if booking_form.start_date >= booking_form.end_date:
                    return clear_booking_form(request, 'Wrong dates!', hotel, room)

                bookings = Booking.objects.filter(room=room)

                for booking in bookings:
                    if booking.start_date <= booking_form.start_date < booking.end_date or booking.start_date < booking_form.end_date <= booking.end_date:
                        return clear_booking_form(request, 'Room is already booked for this dates!', hotel, room)

                booking_form.guest = request.user
                booking_form.room = room
                booking_form.hotel = hotel
                booking_form.save()
                return redirect('booking:booking_confirm', booking_id=booking_form.id)

            else:
                return clear_booking_form(request, 'Invalid form!', hotel, room)

        else:
            return clear_booking_form(request, 'Almost done!', hotel, room)

    else:
        return redirect('auth_login')


def clear_booking_form(request, title, hotel, room):
    title = title
    bookingForm = BookingForm(initial={'hotel': hotel.id})
    context = {
        'bookingForm': bookingForm,
        'title': title,
        'hotel': hotel,
        'room': room,
    }
    return render(request, 'booking/room_bookit.html', context)



def booking_confirm(request, booking_id):
    booking = get_object_or_404(Booking, id=booking_id)

    if request.user.is_authenticated() and request.user.id == booking.guest.id:
        if booking:
            days = booking.end_date.day - booking.start_date.day
            price = days * booking.room.price
            if request.method == 'POST':
                paymentForm = PaymentForm()
                payment_form = paymentForm.save(commit=False)
                payment_form.guest = booking.guest
                payment_form.booking = booking
                payment_form.amount = price
                payment_form.status = False

booking/templates/booking/hotel_detail.html
{% extends 'booking/base.html' %}

{% block style %}
{{ block.super }}

img {
    max-width: 100%;
    height: auto;
}

.hotel_image
{
    width: 600px;
    min-height: 120px;
    max-height: auto;
    float: left;
    padding: 10px;
}

.details
{
    float:left;
    padding: 10px;
    padding-left: 40px;
}


.rooms
{
    clear: both;
    padding: 10px;
}

.room_image
{
    width: 300px;
    min-height: 100px;
    max-height: auto;
    float: left;
    padding: 10px;
}

.room_details
{
    float:left;
    padding: 10px;
}

.empty-div
{
    clear: both;
}

.badge
{
    background-color: #007bff;
}

{% endblock %}

{% block content %}

<div class="hotel_image">
    <a> <img src="{{ hotel.avatar.url }}"> </a>
</div>

<div class="details">

    <h1>{{ hotel.name }} {% if hotel.hotel_chain %} ({{ hotel.hotel_chain.chain_name }}) {% endif %} <span class="badge badge-primary badge"> RATING: {{ hotel.star_rating }}</span></h1>

    <div class="row">
        <div class="col-md-10">
            <h3> <b>Street:</b> {{ hotel.address }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <h3> <b>City:</b> {{ hotel.city }} {{ hotel.country_code }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3><i class="fa fa-envelope" aria-hidden="true" style="color: #cc181e;"></i> <b>Email:</b> {{ hotel.email }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <h3><i class="fa fa-globe" aria-hidden="true" style="color: #2793e8;"></i> <a href="{{ hotel.url }}">Hotel's site</a> </h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">

            <h3><i class="fa fa-phone" aria-hidden="true" style="color: #559900;"></i> <b>Phone:</b> {{ hotel.phone_number }}</h3>
        </div>
    </div>

</div>


<div class="rooms">
    <hr/>
    {% if rooms %}
    <h1>Hotel's Rooms</h1>
        {% for room in rooms %}
            <div class="container">

                <div class="row">

                    <div class="room_image">
                        <img src="{{ room.avatar.url }}">
                    </div>
                    <div class="col-lg-5">
                        <h4><i class="fa fa-bed" aria-hidden="true"></i> <b>Type:</b> {{ room.room_type.room_type }}</h4>
                        <h4>{{ room.room_type.room_standard }}</h4>
                        <h4><b>Smoking:</b> {% if room.room_type.smoking_in %} Yes {% else %} No {% endif %}</h4>
                    </div>

                    <div class="col-lg-3" style="text-align: center;">
                        <h2>${{ room.price }}</h2>
                        <a class="btn btn-lg btn-primary" href="{% url 'booking:room_detail' room.id %}" role="button">View Details</a>
                    </div>
                </div>
            </div>

            <div class="empty-div">
                <hr/>
            </div>
        {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if rooms.has_previous %}
            <a href="?{{ page_var }}={{ rooms.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ rooms.number }} of {{ rooms.paginator.num_pages }}.
            </span>

            {% if rooms.has_next %}
                <a href="?{{ page_var }}={{ rooms.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>

    {% else %}
        <h3>No rooms!</h3>
    {% endif %}
</div>

{% if request.user.is_authenticated and user.is_superuser and user.id == hotel.owner.id %}
<div style="text-align: center;">
    <a class="btn btn-lg btn-primary" href="{% url 'booking:hotel_delete' hotel_id=hotel.id %}" role="button">Delete</a>
</div>
{% endif %}

{% endblock %}

booking/templates/booking/hotels.html
{% extends 'booking/base.html' %}

{% block style %}
{{ block.super }}

img {
    max-width: 100%;
    height: auto;
}

.image_mrr
{
    width: 300px;
    min-height: 120px;
    max-height: auto;
    float: left;
    padding: 10px;
}

.hotel_detail
{
    float: left;
    padding: 10px;
}

.empty-div
{
    clear: both;
}


{% endblock %}

{%  block content %}

    {% if hotels %}
        {% for hotel in hotels %}

            <div class="image_mrr">
                <a> <img src="{{ hotel.avatar.url }}"> </a>
            </div>

            <div class="hotel_detail">
                <a href="{% url 'booking:hotel_detail' hotel.id %}">
                    <h2>{{ hotel.name }} {% if hotel.hotel_chain %} ({{ hotel.hotel_chain.chain_name }}) {% endif %}
                        <span class="badge badge-success">{{ hotel.star_rating }}</span></h2></a>
                <ul>
                    <li>{{ hotel.address }}</li>
                    <li>{{ hotel.city }}</li>
                    <li>{{ hotel.country_code }}</li>
                    <li>{{ hotel.email }}</li>
                    <li>{{ hotel.phone_number }}</li>
                    <li><a href="{{ hotel.url }}">Hotel's site</a> </li>
                    <br>
                </ul>
            </div>

            <div class="empty-div">
            </div>

        <hr/>
        {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if hotels.has_previous %}
            <a href="?{{ page_var }}={{ hotels.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ hotels.number }} of {{ hotels.paginator.num_pages }}.
            </span>

            {% if hotels.has_next %}
                <a href="?{{ page_var }}={{ hotels.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>

    {% else %}
        <h2>There is no hotels in database</h2>
    {% endif %}

{% endblock %}

booking/templates/booking/register.html
{% extends 'booking/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
  <div class="col-md-4 col-sm-offset-4">

      <h1 class="title">Registration</h1>
      <br>

    <form action="" method="post" >
        {{ user_form|crispy }}
        {% csrf_token %}
         <button type="submit" class="btn btn-lg btn-primary">
             Register
         </button>
    </form>
  </div>
</div>

{% endblock %}

booking/templates/booking/room_bookit_confirm.html
{% extends 'booking/base.html' %}

{% block style %}
{{ block.super }}

img {
    max-width: 100%;
    height: auto;
}

.hotel_image
{
    width: 300px;
    min-height: 120px;
    max-height: auto;
    float: left;
    padding: 10px;
}

.bold
{
    color: #00a7ff;
}

{% endblock %}


{% block content %}

<div class="container" style="background-color: #faffa3;">
    <div class="row" style="padding: 15px;">
            <div class="hotel_image">
                <a> <img src="{{ booking.room.avatar.url }}"> </a>
            </div>
        <div class="col-md-4">
            <p><b class="bold">Booked from: </b>{{ booking.start_date }}</p>
            <p><b class="bold"> to: </b> {{ booking.end_date }}</p>
            <p><b class="bold">Hotel: </b> {{ booking.hotel.name }}</p>
            <h2><b style="color: #ff640c;">Price:  ${{ price }}</b></h2>
        </div>
        <div class="col-md-5">
            <form method="post" action="">
                {% csrf_token %}
                <input class="btn btn-lg btn-primary" type="submit" name="submit" value="Confirm Booking" />
            </form>
        </div>
        <div class="col-md-3">
            <a class="btn btn-lg btn-primary" href="{% url 'booking:booking_cancel' booking.id %}" role="button">Cancel</a>
        </div>
    </div>
    <div class="row">

    </div>
</div>

{% endblock %}

booking/templates/booking/room_detail.html
{% extends 'booking/base.html' %}

{% block style %}
{{ block.super }}

img {
    max-width: 100%;
    height: auto;
}

.room_image
{
    width: 600px;
    min-height: 120px;
    max-height: auto;
    float: left;
    padding: 20px;
}

.details
{
    float: none;
    padding: 10px;
    margin-left: 20px;
}

.empty-div
{
    clear: both;
}

{% endblock %}

{% block content %}

<div class="room_image">
    <a> <img src="{{ room.avatar.url }}"> </a>
</div>

<div class="details">
    <h1>Description</h1>
    <p><font size="4">{{ room.description }} </font></p>
    <p><font size="6"> Price: ${{ room.price }} </font></p>
</div>

<div class="empty-div">

</div>

<div class="container">
    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <h3><i class="fa fa-bed" aria-hidden="true"></i> Type: {{ room.room_type.room_type }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <h3>Standard: {{ room.room_type.room_standard }}</h3>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-12" style="text-align: center;">
            <a class="btn btn-lg btn-primary" href="{% url 'booking:room_bookit' room.id %}" role="button">Book It!</a>
        </div>
    </div>

    <hr/>


    {% if comments %}
        <div class="row">
            <div class="col-md-10 col-sm-offset-1">
                <h2>Comments:</h2>
            </div>
        </div>
    <div class="container">
        {% for comment in comments %}

        <div class="well">
            <div class="media">
                <div class="media-body">
                    <h4 class="media-heading"><b>by:</b> <b style="color: #5db7de;">{{ comment.user.username }}</b></h4>
                    <p class="text-right"></p>
                    <p>{{ comment.context }}</p>
                    <ul class="list-inline list-unstyled">
                        <li><span><i class="glyphicon glyphicon-calendar"></i> {{ comment.date }}</span></li>
                        <li>|</li>
                        <li>
                            <b>{{ comment.rating.rate }}</b>
                            {% for i in "xxxxxxxxxx" %}
                                {% if forloop.counter <= comment.rating.rate %}
                                    <span class="glyphicon glyphicon-star" style="color: #f2b01e;"></span>
                                {% else %}
                                    <span class="glyphicon glyphicon-star-empty"></span>
                                {% endif %}
                            {% endfor %}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {%endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if comments.has_previous %}
                <a href="?{{ page_var }}={{ comments.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ comments.number }} of {{ comments.paginator.num_pages }}.
                </span>

                {% if comments.has_next %}
                    <a href="?{{ page_var }}={{ comments.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>

    </div>
    {% else %}
        <div class="row">
            <div class="col-md-10 col-sm-offset-1">
                <h2>There is no comments.</h2>
            </div>
        </div>
    {% endif %}

    {% if user.is_authenticated %}
	<div class="row">
		<div class="col-md-12">
            <form method="POST">
                {% csrf_token %}
                <div class="controls controls-row">
                    <input name="rating" type="number" class="col-md-4 col-sm-offset-2" placeholder="Your rating" min="1" max="10">
                </div>
                <br/>
                <div class="controls">
                    <textarea name="content" class="col-md-8 col-sm-offset-2" placeholder="Your Message" rows="5"></textarea>
                </div>

                <div class="controls col-md-2 col-sm-offset-5">
                    <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-right">Send</button>
                </div>
            </form>
        </div>
	</div>
    <br/>
    {% endif %}
</div>

{% if request.user.is_authenticated and user.is_superuser and room.hotel.owner.id == user.id %}
<div style="text-align: center;">
    <a class="btn btn-lg btn-primary" href="{% url 'booking:room_delete' room_id=room.id %}" role="button">Delete</a>
</div>
{% endif %}


{% endblock %}

booking/templates/booking/user_payments.html
{% extends "booking/user_profile.html" %}

{% block style %}
{{ block.super }}

img {
    max-width: 100%;
    height: auto;
}

.hotel_image
{
    width: 300px;
    min-height: 120px;
    max-height: auto;
    float: left;
    padding: 10px;
}

.bold
{
    color: #00a7ff;
}

{% endblock %}

{% block content %}
{{ block.super }}
{% endblock %}


{% block user_view %}

    {% if payments %}
        <h1>Your Payments:</h1>
        <br/>
        <hr/>
        {% for payment in payments %}
            <div class="row" style="padding: 1px;">
                <div class="col-md-4">
                    <a> <img src="{{ payment.booking.room.avatar.url }}"> </a>
                </div>
                <div class="col-md-4">
                    <p><b class="bold">from: </b>{{ payment.booking.start_date }}</p>
                    <p><b class="bold"> to: </b> {{ payment.booking.end_date }}</p>
                    <p><b class="bold">Hotel: </b> {{ payment.booking.hotel.name }}</p>
                    <p><b style="color: #ff640c;">Price: </b> ${{ payment.amount }}</p>
                    {% if request.user.is_superuser %} <p><b>User: </b> {{ payment.guest.username }}</p> {% endif %}
                </div>
                <div class="col-md-3">
                    {% if payment.status %}
                        <p><b>Status: </b><b style="color: green;"> PAYED</b></p>
                    {% else %}
                        <p><b>Status: </b><b style="color: red;"> NOT PAYED</b></p>
                        <a class="btn btn-lg btn-primary" href="{% url 'booking:pay_bill' payment.id %}" role="button">Pay</a>
                    {% endif %}
                </div>
            </div>
            <hr/>
        {% endfor %}
    {% else %}
        <h1>There is no Payments</h1>
    {% endif %}

{% endblock %}

booking/templates/booking/user_profile.html
{% extends 'booking/base.html' %}

{% block style %}
{{ block.super }}

{% endblock %}

{% block content %}

<div class="container">
{% if request.user.is_authenticated %}

  <div class="row">
    <div class="col-sm-4 col-lg-3">
      <nav class="navbar navbar-default navbar-fixed-side" style="text-align: center;">

          <p><a href="{% url 'auth_password_change' %}">Change Password</a></p>
          <p><a href="{% url 'booking:user_bookings' request.user.username %}">Bookings</a></p>
          <p><a href="{% url 'booking:user_payments' request.user.username %}">Payments</a></p>
          <p><a href="{% url 'auth_password_change' %}">Messages</a></p>

      </nav>
    </div>
    <div class="col-sm-8 col-lg-9" style="text-align: center;">
        {% block user_view %}

        {% if request.user.is_superuser %}
        <a class="btn btn-lg btn-primary" href="{% url 'booking:hotel_chain_add' %}" role="button">Add Hotel Chain</a>
            <a class="btn btn-lg btn-primary" href="{% url 'booking:hotel_add' %}" role="button">Add Hotel</a>
            <a class="btn btn-lg btn-primary" href="{% url 'booking:room_add' %}" role="button">Add Room</a>
            <a class="btn btn-lg btn-primary" href="{% url 'booking:room_type_add' %}" role="button">Add Room Type</a>
        {% endif %}
        {% endblock %}
    </div>
  </div>
{% else %}
    <h1>You're not logged in.</h1>
      <a href="{% url 'auth_login' %}">Login</a>
{% endif %}
</div>



{% endblock %}